# Generated by Django 3.2.8 on 2022-02-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20220219_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
