# Generated by Django 3.2.8 on 2022-02-20 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='featured',
            new_name='featured_image',
        ),
    ]
